# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
        
    - name: Install NPM
      run: npm install
    - name: Running Unit Tests
      run: npm run test:unit 
    - name: Display Softuni username
      run: echo "baido"
  
  # Define the "deploy" job
  deploy:
    # Specify that this job depends on the successful completion of the "build" job
    needs: build

    # Specify the operating system for the job
    runs-on: ubuntu-latest

    # Specify the steps to be executed in the job
    steps:
      # Step 1: Render Deploy Action
      - name: Render Deploy Action
        # Use the "johnbeynon/render-deploy-action" action
        uses: johnbeynon/render-deploy-action@v0.0.8
        with:
          service-id: ${{ secrets.SERVICE_ID }}
          api-key: ${{ secrets.RENDER_API_KEY }}